// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo8aP4sOv5QmvZZB2waaqRQ5WJeqY8mZk',
    appId: '1:613355766380:web:c6ca70722a0972374cce49',
    messagingSenderId: '613355766380',
    projectId: 'cs21-voto',
    authDomain: 'cs21-voto.firebaseapp.com',
    databaseURL: 'https://cs21-voto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cs21-voto.appspot.com',
    measurementId: 'G-R6ECE1R240',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBeMwUlBl5W874Nu4NT0ElsuodjPoi-RY',
    appId: '1:613355766380:android:9767591cda75462a4cce49',
    messagingSenderId: '613355766380',
    projectId: 'cs21-voto',
    databaseURL: 'https://cs21-voto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cs21-voto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHM4-qmO0zLs7-rU2dU46Y_c8Md1oHBY',
    appId: '1:613355766380:ios:40fc06defeaadbd24cce49',
    messagingSenderId: '613355766380',
    projectId: 'cs21-voto',
    databaseURL: 'https://cs21-voto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cs21-voto.appspot.com',
    iosClientId: '613355766380-cnpmtntkqr0t3ov8dmr8qvs3l77nfbqg.apps.googleusercontent.com',
    iosBundleId: 'com.cs21.voto',
  );
}
